name = "leg-go"
main = "api/src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "leg-go-db"
database_id = "04d58397-6904-48e5-986f-21adaebf7d4f"
migrations_dir = "api/drizzle/migrations"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "leg-go-files"

[ai]
binding = "AI"

[vars]
FRONTEND_URL = "http://localhost:5173"
